openapi: "3.0.0"
info:
  version: 1.0.0
  title: Users API
servers:
  - url: http://localhost:8080
paths:
  /users:
    get:
      summary: Endpoint for users data aggregating from multiple databases.
      operationId: getAllUsers
      tags:
        - users
      responses:
        '200':
          description: users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDTO"

    post:
      summary: Endpoint to search users by filtering criteria from multiple databases.
      operationId: searchUsers
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/FilterDTO"
      responses:
        '200':
          description: users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDTO"

components:
  schemas:
    UserDTO:
      required:
        - id
        - name
        - username
        - surname
      properties:
        id:
          type: string
        name:
          type: string
        username:
          type: string
        surname:
          type: string
    FilterDTO:
      required:
        - name
        - value
      properties:
        name:
          type: string
        value:
          type: string